### ISSUE TITLE
Export to PDF

### ISSUE THREAD

**Issue by iamerikjolson** [chenzhiwei/chrome-markdown-editor#3]
I often need to share requirements we keep in GH Issues with non-GH users. To do so, exporting markdown to PDF is a very useful way of sharing. Adding an export to PDF option would be really helpful. Thanks.

**Comment by chenzhiwei** [comment]
Implemented in 0676189 , thanks.

**Comment by iamerikjolson** [comment]
Most excellent. Thank you!
