### ISSUE TITLE
[需求]期望支持Golang语法高亮

### ISSUE THREAD

**Issue by maliyan** [chenzhiwei/chrome-markdown-editor#8]
用这个插件有段时间了，感谢作者！
有个小需求，期望可以支持Golang语法高亮支持，辛苦~~

**Comment by chenzhiwei** [comment]
你指的是 editor 还是 preview 的语法高亮？

**Comment by maliyan** [comment]
> 你指的是 editor 还是 preview 的语法高亮？

不好意思，刚看见消息，期望在preview模式下支持Go语法高亮，另外，还有个小问题，可以支持preview选择字体、大小吗？

**Comment by chenzhiwei** [comment]
已支持语法高亮
